# Site settings
title: Mathematical Puzzle Programs
short-title: MaPP
header-img: "img/bg/silly-walk.jpg"
email: info@mappmath.org
description: "Using puzzles to encourage students to pursue mathematics!"
baseurl: ""
url: "http://mappmath.org"
twitter_username: MaPPmath
github_username:  MaPPmath
facebook_username:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:categories/:year/:month/:day/:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate]
